### ISSUE TITLE
adding optional token to url calling github to avoid rate limit calls

### ISSUE THREAD

**Issue by agustif** [jconsigliere/github-contrib-stats#2]
I'm using  BitBar's GitBar plugin which require's this project.

I'm hitting GH rate api limit's too frequently.

Can I send a PR for this?

**Comment by elquimista** [comment]
Sure. Please feel free to open a PR. Thanks for reporting api limit issue.

**Comment by agustif** [comment]
No problem @elquimista will have a try at this when I can make some time, thank you for open-sourcing the lib! i really love my BitBar plugins as a developer!
